spring:
  profiles:
    actives: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2b8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#
#  redis:
#    database: 3
#    host: localhost
#    jedis:
#      pool:
#        max-idle: 100
#        max-wait: -1ms
#        min-idle: 2
##    password: 123456
#    port: 6379
#    timeout: 2000ms
#mybatis-plus:
#  mapper-locations: mappers/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#
#url:
# protocol: https

  #DataId=${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}