spring:
#  profiles:
#    active: local  #The following profiles are active: local
  main:
    allow-bean-definition-overriding: true
    web-application-type: REACTIVE
  #       # REACTIVE, SERVLET
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 300

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2  #流速 每秒
            redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
            rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
#            key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

jetcache:
  statIntervalMinutes: 3
  areaInCacheName: false
  hidePackages: org.gateway.web
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: jackson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: jackson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs,/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.springboot.cloud: debug
    com.jalja.org.spring: debug
    com.alibaba.nacos.client.*: WARN
  path: logs/
  file:
    max-size: 512mb