spring:
#  profiles:
#    active: local
  main:
    web-application-type: reactive
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 300

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/sc_gateway?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}

#  zipkin:
#    enabled: true
#    sender:
#      type: rabbit
#  sleuth:
#    enabled: true
#    http:
#      legacy:
#        enabled: true

#https://www.jianshu.com/p/f2939ca68df5
jetcache:
  statIntervalMinutes: 3
  areaInCacheName: false
  hidePackages: org.gateway.admin
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: jackson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: jackson  #Jackson fastjson2
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.springboot.cloud.gateway: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 512mb